USE DATABASE WEATHER_DB;

-- Raw weather data table
CREATE TABLE IF NOT EXISTS RAW.WEATHER_DATA (
    ID NUMBER IDENTITY(1,1),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(20),
    TEMPERATURE FLOAT,
    FEELS_LIKE FLOAT,
    TEMP_MIN FLOAT,
    TEMP_MAX FLOAT,
    PRESSURE INT,
    HUMIDITY INT,
    WEATHER_MAIN VARCHAR(50),
    WEATHER_DESCRIPTION VARCHAR(200),
    WIND_SPEED FLOAT,
    CLOUDS INT,
    TEMP_CATEGORY VARCHAR(20),
    COMFORT_INDEX FLOAT,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
)
COMMENT = 'Raw weather data from OpenWeatherMap API';

-- Staging table with data quality checks
CREATE TABLE IF NOT EXISTS STAGING.WEATHER_DATA (
    ID NUMBER AUTOINCREMENT,
    CITY VARCHAR(100),
    TEMPERATURE FLOAT,
    HUMIDITY INT,
    PRESSURE INT,
    WIND_SPEED FLOAT,
    DESCRIPTION VARCHAR(255),
    TIMESTAMP TIMESTAMP_NTZ,
    SAMPLE_ID INT,
    DATA_QUALITY_FLAG VARCHAR(50),
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID)
)
COMMENT = 'Validated and cleaned weather data';